# For more info on HTTP files go to https://aka.ms/vs/httpfile
@apiUrl=https://localhost:1338

@ordinaryUserToken=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImJvYkBhb2wuY29tIiwic3ViIjoiYm9iQGFvbC5jb20iLCJqdGkiOiI4NGFkYzNmNiIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjQzNDY3IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzNjgiLCJodHRwOi8vbG9jYWxob3N0OjEzMzciLCJodHRwczovL2xvY2FsaG9zdDoxMzM4Il0sIm5iZiI6MTcxNzUxNjA2OSwiZXhwIjoxNzI1NDY0ODY5LCJpYXQiOjE3MTc1MTYwNzAsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.NE5vxhsWsSeMzjt1SiG2Q2tE03_kjzN_UnYVYPTIpB8


@softwareCenterUserToken=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InN1ZUBhb2wuY29tIiwic3ViIjoic3VlQGFvbC5jb20iLCJqdGkiOiI3MzdlN2ZhNCIsInJvbGUiOiJTb2Z0d2FyZUNlbnRlciIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjQzNDY3IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzNjgiLCJodHRwOi8vbG9jYWxob3N0OjEzMzciLCJodHRwczovL2xvY2FsaG9zdDoxMzM4Il0sIm5iZiI6MTcxNzUxNjAyNSwiZXhwIjoxNzI1NDY0ODI1LCJpYXQiOjE3MTc1MTYwMjYsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.mZyQtnSQB1sMAl3--m3bpT6r5BRxUvMHe-NFvuZq9C8

# Members of the Software Center can add new items to our catalog of supported software.
# We have a "COLLECTION" of supported software, and we want to APPEND a new subordinate resource (DOCUMENT) to that collection.

POST {{apiUrl}}/catalog
Authorization: {{softwareCenterUserToken}}
Content-Type: application/json

{
  "title": "Notepad",
  "description": "A plain text editor"
}

###

GET {{apiUrl}}/catalog
Authorization: {{ordinaryUserToken}}
###

GET {{apiUrl}}/catalog/0d85702e-3efb-4c8d-8835-4413a7d31910
Authorization: {{ordinaryUserToken}}


### Add An Inn Issue

POST {{apiUrl}}/catalog/c26f955c-2c2c-46b9-a4a1-32c09e3b654a/issues
Authorization: {{ordinaryUserToken}}
Content-Type: application/json

{
  "description": "Want Clippy! Not Copilot!"
}

### Get Support Info

GET {{apiUrl}}/catalog/c26f955c-2c2c-46b9-a4a1-32c09e3b654a/issues/cfffc6a6-0ace-4a7d-ba62-a63e501fc2fa/support
Accept: application/json